db:
  host: "![fRZZb+4tVxLZeo528MAG6QH8XNNvlhq/i1qmL9CHt4D+zm60Ef919w2fTQ7EDDMThHYTmXtwVYl5xlB1V6xlqQ==]"
  port: "![QOOxW3QOhsU=]"
  username: "![Sd7sojT4fS0=]"
  password: "![MQ+ujMz7mEoC/CgAxj37Cw==]"
  database: "![5PyNnCnJ4q3IHxxRYQ+5JA==]"